spring.application.name=rental-eventos
spring.datasource.url=jdbc:postgresql://localhost:5432/rental-eventos
spring.datasource.username=postgres
spring.datasource.password=aluno
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/rental-eventos/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000