spring.application.name=rental-eventos
spring.datasource.url=jdbc:postgresql://localhost:5432/rental-eventos
spring.datasource.username=postgres
spring.datasource.password=aluno
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/rental-eventos/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24xMjM0NTY=
jwt.expiration=86400000